Query Multiple Tables
Saadat123456/vet_clinic_database pull request #3
Opened 2022-04-30 20:38 UTC by Saadat123456

Modify the animals table to reference foreign tables
Update queries to insert and select data

2022-04-30 20:54 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @Saadat123456👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-30 20:54 UTC, thecodechaser commented on schema.sql
> +ALTER TABLE animals ADD owner_id INT;
- [ ] Please add a foreign key to the owner table.
     - You can consider using this code `ALTER TABLE animals ADD owner_id int REFERENCES owners(id);`

2022-04-30 20:54 UTC, thecodechaser commented on schema.sql
> +ALTER TABLE animals ALTER COLUMN species TYPE INT USING species::integer;
- [ ] Please make sure that the column is called species_id and has a foreign key to the species table.
    - You can consider using this code `ALTER TABLE animals ADD species_id int REFERENCES species(id);`

2022-04-30 20:54 UTC, thecodechaser commented on queries.sql
> +SELECT * FROM animals WHERE owner_id=(SELECT id FROM owners WHERE full_name='Melody');
- [ ] Please join the animal and owner table so the query works as expected.
  - You can consider using this code. `SELECT * FROM animals LEFT JOIN owners ON animals.owner_id = owners.id WHERE full_name = 'Melody Pond';`

2022-04-30 20:54 UTC, thecodechaser commented on queries.sql
> +SELECT * FROM animals WHERE species=(SELECT id FROM species WHERE name='Pokemon');
- [ ] Please join the animal and species table so the query works as expected.
  - You can consider using this code. `SELECT * FROM animals LEFT JOIN species ON animals.species_id = species.id WHERE species.name = 'Pokemon';`

2022-05-01 00:04 UTC, codepantha approved these changes
Hi @Saadat123456 👋,

## STATUS: APPROVED ✔️  

Weldone implementing the required changes 👏 👏 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/5oGIdt1xapQ76/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-01 00:07 UTC, merged